import { Header } from "./components/Header";
import "./styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-400 text-xl">
        <div className="w-2/3 flex flex-col gap-2 bg-slate-500 mx-auto">
          <Header />
          <div className="p-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
